// Package shared is generated by protoactor-go/protoc-gen-gograin@0.1.0
package shared

import (
	"errors"
	"fmt"
	"math"
	"time"

	"github.com/asynkron/protoactor-go/actor"
	"github.com/asynkron/protoactor-go/cluster"
	logmod "github.com/asynkron/protoactor-go/log"
	"google.golang.org/protobuf/proto"
)

var (
	plog = logmod.New(logmod.InfoLevel, "[GRAIN][shared]")
	_    = proto.Marshal
	_    = fmt.Errorf
	_    = math.Inf
)

// SetLogLevel sets the log level.
func SetLogLevel(level logmod.Level) {
	plog.SetLevel(level)
}

var xSchedulerFactory func() Scheduler

// SchedulerFactory produces a Scheduler
func SchedulerFactory(factory func() Scheduler) {
	xSchedulerFactory = factory
}

// GetSchedulerGrainClient instantiates a new SchedulerGrainClient with given Identity
func GetSchedulerGrainClient(c *cluster.Cluster, id string) *SchedulerGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &SchedulerGrainClient{Identity: id, cluster: c}
}

// GetSchedulerKind instantiates a new cluster.Kind for Scheduler
func GetSchedulerKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SchedulerActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Scheduler", props)
	return kind
}

// GetSchedulerKind instantiates a new cluster.Kind for Scheduler
func NewSchedulerKind(factory func() Scheduler, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xSchedulerFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SchedulerActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Scheduler", props)
	return kind
}

// Scheduler interfaces the services available to the Scheduler
type Scheduler interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	Schedule(*ScheduleRequest, cluster.GrainContext) (*ScheduleResponse, error)
}

// SchedulerGrainClient holds the base data for the SchedulerGrain
type SchedulerGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// Schedule requests the execution on to the cluster with CallOptions
func (g *SchedulerGrainClient) Schedule(r *ScheduleRequest, opts ...cluster.GrainCallOption) (*ScheduleResponse, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Call(g.Identity, "Scheduler", reqMsg, opts...)
	if err != nil {
		return nil, err
	}
	switch msg := resp.(type) {
	case *cluster.GrainResponse:
		result := &ScheduleResponse{}
		err = proto.Unmarshal(msg.MessageData, result)
		if err != nil {
			return nil, err
		}
		return result, nil
	case *cluster.GrainErrorResponse:
		return nil, errors.New(msg.Err)
	default:
		return nil, errors.New("unknown response")
	}
}

// SchedulerActor represents the actor structure
type SchedulerActor struct {
	ctx     cluster.GrainContext
	inner   Scheduler
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *SchedulerActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xSchedulerFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &ScheduleRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				plog.Error("Schedule(ScheduleRequest) proto.Unmarshal failed.", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			r0, err := a.inner.Schedule(req, a.ctx)
			if err != nil {
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			bytes, err := proto.Marshal(r0)
			if err != nil {
				plog.Error("Schedule(ScheduleRequest) proto.Marshal failed", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			resp := &cluster.GrainResponse{MessageData: bytes}
			ctx.Respond(resp)

		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

var xInventoryFactory func() Inventory

// InventoryFactory produces a Inventory
func InventoryFactory(factory func() Inventory) {
	xInventoryFactory = factory
}

// GetInventoryGrainClient instantiates a new InventoryGrainClient with given Identity
func GetInventoryGrainClient(c *cluster.Cluster, id string) *InventoryGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &InventoryGrainClient{Identity: id, cluster: c}
}

// GetInventoryKind instantiates a new cluster.Kind for Inventory
func GetInventoryKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &InventoryActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Inventory", props)
	return kind
}

// GetInventoryKind instantiates a new cluster.Kind for Inventory
func NewInventoryKind(factory func() Inventory, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xInventoryFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &InventoryActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Inventory", props)
	return kind
}

// Inventory interfaces the services available to the Inventory
type Inventory interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	Describe(*DescribeInventoryRequest, cluster.GrainContext) (*DescribeInventoryResponse, error)
	StartBuild(*BuildRequest, cluster.GrainContext) (*BuildResponse, error)
}

// InventoryGrainClient holds the base data for the InventoryGrain
type InventoryGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// Describe requests the execution on to the cluster with CallOptions
func (g *InventoryGrainClient) Describe(r *DescribeInventoryRequest, opts ...cluster.GrainCallOption) (*DescribeInventoryResponse, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Call(g.Identity, "Inventory", reqMsg, opts...)
	if err != nil {
		return nil, err
	}
	switch msg := resp.(type) {
	case *cluster.GrainResponse:
		result := &DescribeInventoryResponse{}
		err = proto.Unmarshal(msg.MessageData, result)
		if err != nil {
			return nil, err
		}
		return result, nil
	case *cluster.GrainErrorResponse:
		return nil, errors.New(msg.Err)
	default:
		return nil, errors.New("unknown response")
	}
}

// StartBuild requests the execution on to the cluster with CallOptions
func (g *InventoryGrainClient) StartBuild(r *BuildRequest, opts ...cluster.GrainCallOption) (*BuildResponse, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes}
	resp, err := g.cluster.Call(g.Identity, "Inventory", reqMsg, opts...)
	if err != nil {
		return nil, err
	}
	switch msg := resp.(type) {
	case *cluster.GrainResponse:
		result := &BuildResponse{}
		err = proto.Unmarshal(msg.MessageData, result)
		if err != nil {
			return nil, err
		}
		return result, nil
	case *cluster.GrainErrorResponse:
		return nil, errors.New(msg.Err)
	default:
		return nil, errors.New("unknown response")
	}
}

// InventoryActor represents the actor structure
type InventoryActor struct {
	ctx     cluster.GrainContext
	inner   Inventory
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *InventoryActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xInventoryFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &DescribeInventoryRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				plog.Error("Describe(DescribeInventoryRequest) proto.Unmarshal failed.", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			r0, err := a.inner.Describe(req, a.ctx)
			if err != nil {
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			bytes, err := proto.Marshal(r0)
			if err != nil {
				plog.Error("Describe(DescribeInventoryRequest) proto.Marshal failed", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			resp := &cluster.GrainResponse{MessageData: bytes}
			ctx.Respond(resp)
		case 1:
			req := &BuildRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				plog.Error("StartBuild(BuildRequest) proto.Unmarshal failed.", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			r0, err := a.inner.StartBuild(req, a.ctx)
			if err != nil {
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			bytes, err := proto.Marshal(r0)
			if err != nil {
				plog.Error("StartBuild(BuildRequest) proto.Marshal failed", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			resp := &cluster.GrainResponse{MessageData: bytes}
			ctx.Respond(resp)

		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

var xTimerFactory func() Timer

// TimerFactory produces a Timer
func TimerFactory(factory func() Timer) {
	xTimerFactory = factory
}

// GetTimerGrainClient instantiates a new TimerGrainClient with given Identity
func GetTimerGrainClient(c *cluster.Cluster, id string) *TimerGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &TimerGrainClient{Identity: id, cluster: c}
}

// GetTimerKind instantiates a new cluster.Kind for Timer
func GetTimerKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &TimerActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Timer", props)
	return kind
}

// GetTimerKind instantiates a new cluster.Kind for Timer
func NewTimerKind(factory func() Timer, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xTimerFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &TimerActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Timer", props)
	return kind
}

// Timer interfaces the services available to the Timer
type Timer interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	Start(*StartTimerRequest, cluster.GrainContext) (*Noop, error)
}

// TimerGrainClient holds the base data for the TimerGrain
type TimerGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// Start requests the execution on to the cluster with CallOptions
func (g *TimerGrainClient) Start(r *StartTimerRequest, opts ...cluster.GrainCallOption) (*Noop, error) {
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Call(g.Identity, "Timer", reqMsg, opts...)
	if err != nil {
		return nil, err
	}
	switch msg := resp.(type) {
	case *cluster.GrainResponse:
		result := &Noop{}
		err = proto.Unmarshal(msg.MessageData, result)
		if err != nil {
			return nil, err
		}
		return result, nil
	case *cluster.GrainErrorResponse:
		return nil, errors.New(msg.Err)
	default:
		return nil, errors.New("unknown response")
	}
}

// TimerActor represents the actor structure
type TimerActor struct {
	ctx     cluster.GrainContext
	inner   Timer
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *TimerActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xTimerFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &StartTimerRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				plog.Error("Start(StartTimerRequest) proto.Unmarshal failed.", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			r0, err := a.inner.Start(req, a.ctx)
			if err != nil {
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			bytes, err := proto.Marshal(r0)
			if err != nil {
				plog.Error("Start(StartTimerRequest) proto.Marshal failed", logmod.Error(err))
				resp := &cluster.GrainErrorResponse{Err: err.Error()}
				ctx.Respond(resp)
				return
			}
			resp := &cluster.GrainResponse{MessageData: bytes}
			ctx.Respond(resp)

		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}
